### ISSUE TITLE
Readme update with pipeline examples

### ISSUE THREAD

**Issue by jonesbusy** [jenkinsci/file-operations-plugin#75]
### Describe your use-case which is not covered by existing documentation.

Readme is missing example of of pipeline steps

We can do something similar to JobDSL https://github.com/jenkinsci/file-operations-plugin/blob/main/docs/JOB-DSL.md

**Comment by Gokhul26** [comment]
Hi @jonesbusy ,

I'd like to work on this issue and contribute to updating the README with pipeline examples. I'll start by adding some examples similar to those in the JobDSL documentation.

Please let me know if there's anything specific you'd like to see included.

Thanks!

**Comment by Gokhul26** [comment]
@jonesbusy , I've updated the README.md for Copy, Delete, Create and Download operations. If you like the way I edited the README file, then let me know to work on all other operations that you wanted to be presented in the README file.
